file1=open("30 days 30 hours operations.txt","w+")
file1.write("I have completed 10days successfully \n")
file1.close( )
file1=open("30 days 30 hours operations.txt","r+")
print(file1.read( ))
file1=open("30days 30hours operations.txt","a+")
file1.write("Deepika \n")
file1.close( )
file1=open("30days 30hours operations.txt","r+")
print(file1.read( ))